ticksUntilDeath = 2400
continueTimerWhileOffline = true
rescueActionTicks = 40
rescueRespawnHealth = 1
rescueRespawnFoodLevel = 5
rescueRespawnEffects = ["minecraft:hunger|600|0", "minecraft:weakness|1200|0", "minecraft:blindness|600|0"]
rescueDistance = 5.0
glowOnKnockout = false
allowUnarmedMelee = false
allowBows = false
allowPistols = false
