contributorCosmetic = ""
globalTooltip = false
tooltipWrapWidth = 200
noMicrosoftTelemetry = true

[debug]
tagsTooltip = false
debugTooltipMsg = true
NBTTooltipFormatter = "vanilla"
NBTTooltip = false
